// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvsagudksxmdrmnhgymi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2c2FndWRrc3htZHJtbmhneW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDE0ODcsImV4cCI6MjA3MjI3NzQ4N30.a5e_teJKo7zSu-v6YSDEjV8YUkvCXAxwooovIIEMzh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});